namespace Moth.Tasks
{
    using System;

    /* -------------------------------------------- *
     * Generated by TaskQueueActions.tt T4 template *
     * This file should not be edited manually.     *
     * -------------------------------------------- */

    public partial class TaskQueue
    {
        /// <summary>
        /// Enqueue an action to be run later.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue (Action action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask (action));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1> (Action<T1> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2> (Action<T1, T2> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3> (Action<T1, T2, T3> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4> (Action<T1, T2, T3, T4> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5> (Action<T1, T2, T3, T4, T5> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6> (Action<T1, T2, T3, T4, T5, T6> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7> (Action<T1, T2, T3, T4, T5, T6, T7> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8> (Action<T1, T2, T3, T4, T5, T6, T7, T8> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg12">12th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T12">The type of the 12th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg12">12th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg13">13th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T12">The type of the 12th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T13">The type of the 13th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg12">12th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg13">13th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg14">14th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T12">The type of the 12th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T13">The type of the 13th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T14">The type of the 14th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg12">12th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg13">13th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg14">14th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg15">15th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T12">The type of the 12th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T13">The type of the 13th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T14">The type of the 14th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T15">The type of the 15th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }

        /// <summary>
        /// Enqueue an action to be run later with supplied arguments.
        /// </summary>
        /// <param name="action">Action to enqueue.</param>
        /// <param name="arg1">1st argument to run <paramref name="action"/> with.</param>
        /// <param name="arg2">2nd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg3">3rd argument to run <paramref name="action"/> with.</param>
        /// <param name="arg4">4th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg5">5th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg6">6th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg7">7th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg8">8th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg9">9th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg10">10th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg11">11th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg12">12th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg13">13th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg14">14th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg15">15th argument to run <paramref name="action"/> with.</param>
        /// <param name="arg16">16th argument to run <paramref name="action"/> with.</param>
        /// <typeparam name="T1">The type of the 1st parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T2">The type of the 2nd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T3">The type of the 3rd parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T4">The type of the 4th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T5">The type of the 5th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T6">The type of the 6th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T7">The type of the 7th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T8">The type of the 8th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T9">The type of the 9th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T10">The type of the 10th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T11">The type of the 11th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T12">The type of the 12th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T13">The type of the 13th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T14">The type of the 14th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T15">The type of the 15th parameter of <paramref name="action"/>.</typeparam>
        /// <typeparam name="T16">The type of the 16th parameter of <paramref name="action"/>.</typeparam>
        /// <exception cref="ArgumentNullException"><paramref name="action"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">The <see cref="TaskQueue"/> has been disposed.</exception>
        public void Enqueue<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> (Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> action)
        {
            if (action == null)
            {
                throw new ArgumentNullException (nameof (action));
            }

            Enqueue (new DelegateTask<T> (action, arg));
        }
	}
}